name: mangai.tech
on:
  push:
    branches:
      - 'main'
      - 'production'
  workflow_dispatch:

env:
  POSTGRES_DB: bad_project_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install 
          yarn knex migrate:latest --env test
          cd test
          yarn jest ./on9.test.ts
          yarn jest ./UserController.test.ts
          yarn jest ./UserService.test.ts
          yarn jest ./UserIntegration.test.ts
        # working-directory: ./03_BAD/BAD005/memo_wall
  deploy:
      if: github.ref_name == 'production'
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - name: ssh to pull latest version
        uses: fifsky/ssh-action@master
        with:
          command: |
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            forever restart index.js
          host: mangai.tech
          user: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}